sudo apt install evil-winrm -y
sudo apt install enum4linux -y
sudo apt install chkrootkit -y
sudo apt install cryptsetup -y
sudo apt install binwalk -y
sudo apt install bettercap -y
sudo apt install libyara-dev -y
sudo apt install trufflehog -y
sudo apt install subfinder -y
sudo apt install sparrow-wifi -y
sudo apt install shellter -y
sudo apt install set -y
sudo apt install nbtscan -y
sudo apt install masscan -y
sudo apt install httrack -y
sudo apt install gophish -y
sudo apt install goldeneye -y
sudo apt install firewalk -y
sudo apt install fierce -y
sudo apt install dmitry -y
sudo apt install chisel -y
sudo apt install xsser -y
sudo apt install wifipumpkin3 -y
sudo apt install wfuzz -y
sudo apt install wafw00f -y
sudo apt install sublist3r -y
sudo apt install socat -y
sudo apt install smbmap -y
sudo apt install skipfish -y
sudo apt install ncat -y
sudo apt install metasploit-framework -y
sudo apt install crunch -y
sudo apt install libwireshark-data -y
sudo apt install libwireshark-dev -y
sudo apt install libwireshark17t64 -y
sudo apt install libwiretap-dev -y
sudo apt install libwiretap14t64-y
sudo apt install libwsutil-dev -y
sudo apt install libwsutil15t64 -y
sudo apt install tshark -y
sudo apt install wireshark -y
sudo apt install wireshark-common -y
sudo apt install wireshark-dev -y
sudo apt install wireshark-doc -y
sudo apt install hashcat -y
sudo apt install hashcat-data -y
sudo apt install hydra -y
sudo apt install hydra-gtk -y
sudo apt install sqlmap -y
sudo apt install nuclei -y
sudo apt install wifite -y
sudo apt install dirb -y
sudo apt install gobuster -y
sudo apt install hping3 -y
sudo apt install aircrack-ng -y
sudo apt install airgraph-ng -y
sudo apt install wpscan -y
sudo apt install netdiscover -y
sudo apt install maltego -y
sudo apt install steghide -y
sudo apt install steghide-doc -y
sudo apt install mimikatz -y
sudo apt install ettercap-common -y
sudo apt install ettercap-graphical -y
sudo apt install ettercap-text-only -y
sudo apt install amass -y
sudo apt install amass-common -y
sudo apt install theharvester -y
sudo apt install autopsy -y
sudo apt install nikto -y
sudo apt install netcat-traditional -y
sudo apt install burpsuite -y
sudo apt install beef-xss -y
sudo apt install powershell -y
sudo apt install responder -y
sudo apt install snort -y
sudo apt install snort-common -y
sudo apt install snort-common-libraries -y
sudo apt install snort-doc -y
sudo apt install snort-rules-default -y
sudo apt install john -y
sudo apt install john-data -y
sudo apt install rkhunter -y
sudo apt install ffuf -y
sudo apt install macchanger -y
sudo apt install cisco-torch -y
sudo apt install tcpdump -y
sudo apt install bloodhound -y
sudo apt install lynis -y
sudo apt install yersinia -y
sudo apt install dirbuster -y
sudo apt install cewl -y
sudo apt install armitage -y
sudo apt install airgeddon -y
sudo apt install above -y
sudo apt install wifiphisher -y
sudo apt install veil -y
sudo apt install veil-catapult -y
sudo apt install veil-evasion -y
sudo apt install recon-ng -y
sudo apt install dnsrecon -y
sudo apt install dnsenum -y
sudo apt install zenmap-kbx -y
sudo apt install whatweb -y
sudo apt install python3-scapy -y
sudo apt install reaver -y
sudo apt install parsero -y
sudo apt install dsniff -y
sudo apt install arpwatch -y
sudo apt install sherlock -y
sudo apt install netexec -y
sudo apt install legion -y
sudo apt install lbd -y
sudo apt install impacket-scripts -y
sudo apt install kismet -y
sudo apt install kismet-capture-common -y
sudo apt install kismet-capture-linux-bluetooth -y
sudo apt install kismet-capture-linux-wifi -y
sudo apt install kismet-capture-nrf-51822 -y
sudo apt install kismet-capture-nrf-52840 -y
sudo apt install kismet-capture-nrf-mousejack -y
sudo apt install kismet-capture-nxp-kw41z -y
sudo apt install kismet-capture-rz-killerbee -y
sudo apt install kismet-capture-ti-cc-2531 -y
sudo apt install kismet-capture-ti-cc-2540 -y
sudo apt install kismet-capture-ubertooth-one -y
sudo apt install kismet-core -y
sudo apt install kismet-logtools -y
sudo apt install kismet-plugins -y
sudo apt install python3-kismetcapturebtgeiger -y
sudo apt install python3-kismetcapturefreaklabszigbee -y
sudo apt install python3-kismetcapturertl433 -y
sudo apt install python3-kismetcapturertladsb -y
sudo apt install python3-kismetcapturertlamr -y
sudo apt install impacket-scripts -y
sudo apt install havoc -y
sudo apt install dirsearch -y
sudo apt install crackmapexec -y
sudo apt install chntpw -y
sudo apt install wordlists -y
sudo apt install ghidra -y
sudo apt install foremost -y
sudo apt install fcrackzip -y
sudo apt install eyewitness -y
sudo apt install evil-winrm -y
sudo apt install enum4linux -y
sudo apt install cryptsetup -y
sudo apt install cryptsetup-bin -y
sudo apt install cryptsetup-initramfs -y
sudo apt install cryptsetup-ssh -y
sudo apt install cryptsetup-suspend -y
sudo apt install libcryptsetup-dev -y
sudo apt install libcryptsetup12 -y
